apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-main-env-vars
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.main.envVars }}
  "{{ $key }}": "{{ $val | b64enc }}"
  {{- end }}
