{{- $ctx := merge (dict) . (dict "component" "main") -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-main
  labels:
    {{- include "app.labels" $ctx | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/main-env-vars: {{ include (print $.Template.BasePath "/main-env-vars-secret.yaml") . | sha256sum }}
      labels:
        {{- include "app.labels" $ctx | nindent 8 }}
    spec:
      containers:
        - name: main
          image: {{ $.Values.werf.image.main }}
          ports:
            - name: http
              containerPort: 3000
          resources:
            {{- toYaml .Values.main.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "app.fullname" . }}-main-env-vars
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
