{{- $ctx := merge (dict) . (dict "component" "zero-cache") -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-zero-cache-env-vars
  labels:
    {{- include "app.labels" $ctx | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.zero.envVars }}
  "{{ $key }}": "{{ $val | toString | b64enc }}"
  {{- end }}
